<a href="https://colab.research.google.com/github/riiya-patel/urban-octo-funicular/blob/master/Cluster_Analysis_using_Kmeans_Clustering_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction

K-Means clustering algorithm represents each cluster by its corresponding cluster centroid.

In [38]:
import pandas as pd

In [39]:
Ratings=[['John',5,5,2,1],['Mary', 4,5,3,2],['Bob',4,4,4,3],['Lisa',2,2,4,5],['Lee', 1,2,3,4],['Harry',2,1,5,5]]

In [40]:
Ratings

[['John', 5, 5, 2, 1],
 ['Mary', 4, 5, 3, 2],
 ['Bob', 4, 4, 4, 3],
 ['Lisa', 2, 2, 4, 5],
 ['Lee', 1, 2, 3, 4],
 ['Harry', 2, 1, 5, 5]]

In [41]:
Titles=['User','Jaws','Star Wars','Exorcist','Omen']

In [42]:
Titles

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [43]:
movies=pd.DataFrame(Ratings, columns=Titles)

In [44]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0   John     5          5         2     1
1   Mary     4          5         3     2
2    Bob     4          4         4     3
3   Lisa     2          2         4     5
4    Lee     1          2         3     4
5  Harry     2          1         5     5

# Data Discussion


From the dataset the first three users like action movies, and the last three users enjoy horror movies. Our goal is to apply k means of clustering on the users to identify groups of users with similar movie preferences k=2 from the dataset


In [45]:
from sklearn import cluster

In [46]:
myData=movies.drop('User', axis=1)

In [47]:
myData

Jaws  Star Wars  Exorcist  Omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [48]:
k_means=cluster.KMeans(n_clusters=2, max_iter=50, random_state=1)

In [49]:
k_means

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=50,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=1, tol=0.0001, verbose=0)

In [50]:
k_means.fit(myData)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=50,
       n_clusters=2, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=1, tol=0.0001, verbose=0)

In [51]:
labels=k_means.labels_

In [52]:
labels

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [53]:
pd.DataFrame(labels, index=movies.User, columns=['Cluster ID'])

Cluster ID
User             
John            0
Mary            0
Bob             0
Lisa            1
Lee             1
Harry           1

In [54]:
 centroids=k_means.cluster_centers_
 

In [55]:
centroids

array([[4.33333333, 4.66666667, 3.        , 2.        ],
       [1.66666667, 1.66666667, 4.        , 4.66666667]])

In [56]:
pd.DataFrame(centroids,columns=myData.columns)

Jaws  Star Wars  Exorcist      Omen
0  4.333333   4.666667       3.0  2.000000
1  1.666667   1.666667       4.0  4.666667

In [57]:
import numpy as np

In [58]:
testData=np.array([[4,5,1,2],[3,2,4,4],[2,3,4,1],[3,2,3,3],[5,4,1,4]])

In [59]:
testData

array([[4, 5, 1, 2],
       [3, 2, 4, 4],
       [2, 3, 4, 1],
       [3, 2, 3, 3],
       [5, 4, 1, 4]])

In [60]:
labels=k_means.predict(testData)

In [61]:
labels

array([0, 1, 0, 1, 0], dtype=int32)

In [62]:
labels=labels.reshape(-1,1)

In [63]:
labels

array([[0],
       [1],
       [0],
       [1],
       [0]], dtype=int32)

In [64]:
usernames=np.array(['Paul','Kim','Liz','Tom','Bill']).reshape(-1,1)

In [65]:
cols=movies.columns.tolist()

In [66]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [67]:
cols.append('Cluster ID')

In [68]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen', 'Cluster ID']

In [69]:
newusers=pd.DataFrame(np.concatenate((usernames,testData,labels), axis=1),columns=cols)

In [70]:
newusers

User Jaws Star Wars Exorcist Omen Cluster ID
0  Paul    4         5        1    2          0
1   Kim    3         2        4    4          1
2   Liz    2         3        4    1          0
3   Tom    3         2        3    3          1
4  Bill    5         4        1    4          0

In [71]:
myData

Jaws  Star Wars  Exorcist  Omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [72]:
k_means.cluster_centers_

array([[4.33333333, 4.66666667, 3.        , 2.        ],
       [1.66666667, 1.66666667, 4.        , 4.66666667]])

# Future work

how to determine the number of clusters. we looked at the  data and concluded that 2 clusters are okay. 